# Generated by Django 5.0.6 on 2024-06-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='teste',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='account_image',
            field=models.ImageField(blank=True, null=True, upload_to='account_image/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=15, null=True),
        ),
    ]
