# Generated by Django 5.0.6 on 2024-06-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_products'),
        ('product', '0004_alter_productvariation_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='product.productvariation'),
        ),
    ]
