# Generated by Django 5.0.6 on 2024-05-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aceito'), ('S', 'Enviado'), ('E', 'Entregue')], max_length=1)),
                ('total', models.PositiveIntegerField()),
                ('products', models.ManyToManyField(blank=True, to='product.productvariation')),
            ],
        ),
    ]
