# Generated by Django 5.0.6 on 2024-05-25 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_andress_city_alter_andress_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='destiny',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.andress'),
        ),
    ]
